snowflake-dwh:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: upgppaj-ejb38951

      # User/password auth
      user: JANEROSE
      password: ${DBT_DW_PASSWORD}

      role: ACCOUNTADMIN
      database: RAW
      warehouse: COMPUTE_WH
      schema: dbt_janerose
      threads: 4
      client_session_keep_alive: True
      query_tag: dbt_eon

      # optional settings
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)